DROP TABLE IF EXISTS SurrogateKeys;
DROP TABLE IF EXISTS CommentDetails;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS PostDetails;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS UserDetails;
DROP TABLE IF EXISTS Users;

CREATE TABLE SurrogateKeys(
  TableName VARCHAR(50) NOT NULL,
  KeyValue BIGINT NOT NULL,
  PRIMARY KEY (TableName)
) Engine = InnoDB;

CREATE TABLE Users(
  ID INTEGER NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  NickName VARCHAR(50) NOT NULL,
  UserType VARCHAR(20) NOT NULL, /* REAL, AUTOGEN */
  CreatedTime TIMESTAMP NOT NULL,
  Deleted BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
) Engine = InnoDB;

CREATE TABLE UserDetail(
  ID INTEGER NOT NULL,
  UserID INTEGER NOT NULL,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  BlogAddress VARCHAR(255) NOT NULL,
  BirthDate VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (UserID) REFERENCES Users(ID)
) Engine = InnoDB;

CREATE TABLE Categories(
  ID INTEGER NOT NULL,
  OwnerID INTEGER NOT NULL,
  ParentID INTEGER NOT NULL,
  CategoryName VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (OwnerID) REFERENCES Users(ID),
  FOREIGN KEY (ParentID) REFERENCES Categories(ID)
) Engine = InnoDB;

CREATE TABLE Posts(
  ID INTEGER NOT NULL,
  OwnerID INTEGER NOT NULL,
  CategoryID INTEGER NOT NULL,
  Title TEXT NOT NULL,
  CreatedTime TIMESTAMP NOT NULL,
  ModifiedTime TIMESTAMP NOT NULL,
  Deleted BOOLEAN NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (OwnerID) REFERENCES Users(ID),
  FOREIGN KEY (CategoryID) REFERENCES Categories(ID)
) Engine = InnoDB;

CREATE TABLE PostDetails(
  ID INTEGER NOT NULL,
  PostID INTEGER NOT NULL,
  Text TEXT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PostID) REFERENCES Posts(ID)
) Engine = InnoDB;

CREATE TABLE Comments(
  ID INTEGER NOT NULL,
  OwnerID INTEGER NOT NULL,
  PostID INTEGER NOT NULL,
  CreatedTime TIMESTAMP NOT NULL,
  ModifiedTime TIMESTAMP NOT NULL,
  Deleted BOOLEAN NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (OwnerID) REFERENCES Users(ID),
  FOREIGN KEY (PostID) REFERENCES Posts(ID)
) Engine = InnoDB;

CREATE TABLE CommentDetails(
  ID INTEGER NOT NULL,
  CommentID INTEGER NOT NULL,
  Text TEXT NOT NULL,
  PRIMARY KEY(ID),
  FOREIGN KEY (CommentID) REFERENCES Comments(ID)
) Engine = InnoDB;